import * as fs from 'fs';
import * as path from 'path';

export interface TestResult {
  name: string;
  status: 'pass' | 'fail' | 'skip';
  duration: number;
  error?: string;
}

export interface TestSuiteResult {
  suiteName: string;
  timestamp: string;
  totalTests: number;
  passed: number;
  failed: number;
  skipped: number;
  duration: number;
  tests: TestResult[];
  screenshots: string[];
}

export class TestReporter {
  private results: TestSuiteResult;

  constructor(suiteName: string) {
    this.results = {
      suiteName,
      timestamp: new Date().toISOString(),
      totalTests: 0,
      passed: 0,
      failed: 0,
      skipped: 0,
      duration: 0,
      tests: [],
      screenshots: [],
    };
  }

  addTest(test: TestResult) {
    this.results.tests.push(test);
    this.results.totalTests++;

    if (test.status === 'pass') {
      this.results.passed++;
    } else if (test.status === 'fail') {
      this.results.failed++;
    } else if (test.status === 'skip') {
      this.results.skipped++;
    }
  }

  addScreenshot(filePath: string) {
    this.results.screenshots.push(filePath);
  }

  setDuration(duration: number) {
    this.results.duration = duration;
  }

  getResults(): TestSuiteResult {
    return this.results;
  }

  generateMarkdown(): string {
    const markdown = `# Deployment Test Results

**Generated:** ${new Date(this.results.timestamp).toLocaleString()}

## Summary

| Metric | Value |
|--------|-------|
| Suite Name | ${this.results.suiteName} |
| Total Tests | ${this.results.totalTests} |
| Passed | ${this.results.passed} ✅ |
| Failed | ${this.results.failed} ❌ |
| Skipped | ${this.results.skipped} ⏭️ |
| Total Duration | ${(this.results.duration / 1000).toFixed(2)}s |
| Status | ${this.results.failed === 0 ? '✅ PASS' : '❌ FAIL'} |

## Test Details

${this.results.tests
  .map(
    (test) => `
### ${test.name}

**Status:** ${test.status === 'pass' ? '✅ PASS' : test.status === 'fail' ? '❌ FAIL' : '⏭️ SKIP'}  
**Duration:** ${(test.duration / 1000).toFixed(3)}s
${test.error ? `**Error:** ${test.error}` : ''}
`
  )
  .join('\n')}

## Screenshots

${
  this.results.screenshots.length > 0
    ? this.results.screenshots
        .map((screenshot) => {
          const fileName = path.basename(screenshot);
          return `- ![${fileName}](${screenshot})`;
        })
        .join('\n')
    : 'No screenshots captured.'
}

## Deployment Status

**Overall Status:** ${this.results.failed === 0 ? '✅ PASS' : '❌ FAIL'}

${
  this.results.failed === 0
    ? `
All tests passed! The application is ready for deployment.

### Verified Capabilities:
- ✅ Application loads successfully at localhost:4200
- ✅ Key DOM elements are present and visible
- ✅ No critical console errors detected
- ✅ Drag-drop functionality working correctly
- ✅ UI state updates properly during operations
- ✅ Multiple operations handled without lag
`
    : `
**Issues Found:**

${this.results.tests
  .filter((t) => t.status === 'fail')
  .map((t) => `- ${t.name}: ${t.error || 'Unknown error'}`)
  .join('\n')}

### Recommendations:
1. Review failed tests above
2. Check browser console for errors
3. Verify app state after failed operations
4. Consider environment-specific issues
`
}

---

Generated by Playwright Deployment Testing Suite
`;

    return markdown;
  }
}

export function collectScreenshots(directory: string): string[] {
  if (!fs.existsSync(directory)) {
    return [];
  }

  return fs
    .readdirSync(directory)
    .filter((file) => /\.(png|jpg|jpeg|gif)$/i.test(file))
    .map((file) => path.join(directory, file));
}
